<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<div class="container">
    <ul class="pager">
        <li class="previous">
            <?php echo $this->tag->linkTo([
                "",
                "&larr; Home",
            ]); ?>
        </li>
    </ul>
    <h1>Descriptin view</h1>
    <?php
    echo $description;
    var_dump($pId);
    ?>
</div>
