<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">    
<div class="container">
    <?php echo $this->getContent() ?>

    <?php
    echo $this->tag->linkTo(["", "back", "class" => "btn btn-default active"]);
    echo "<br />";
    ?>
    <form method='post' action="create">
      <fieldset>

        <legend>Create new product</legend>

        <div>
          <label for="partner_id">Partner: </label>
          <?php echo $form->render('partner_id'); ?>
        </div>
        <div>
          <label for="name">Name: </label>
          <?php echo $form->render('name'); ?>
        </div>
        <div>
          <label for="description">Description: </label>
          <?php echo $form->render('description'); ?>
        </div>
        <div>
          <label for="availability">Availability: </label>
          <?php echo $form->render('availability'); ?>
        </div>
        <div>
          <label for="currency">Currency: </label>
          <?php echo $form->render('currency'); ?>
        </div>
        <div>
          <label for="price">Price: </label>
          <?php echo $form->render('price'); ?>
        </div>

        <p>
            <input type='submit' value='Save' class="btn btn-primary"/>
        </p>

      </fieldset>
    </form>
</div>