<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<div class="container">
<ul class="pager">
    <li class="previous">
        <?php echo $this->tag->linkTo([
                "",
                "&larr; Home", 
        ]); ?>  
    </li>
</ul>
<br />
<h1><?= $title;?></h1>
<br />
<table class="table table-striped">
    <thead>
        <tr>
            <th>Partner's Id </th>
            <th>Name </th>
            <th>Description </th>
            <th>Price </th>
            <th>Currency </th>
            <th>Availablity </th>
            <th>Created </th>
            <th>...</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($products as $product) {
        echo "<tr><td>",$product->partner_id, "</td><td>",
            $product->name, "</td><td>",
            $product->description, "</td><td>",
            $product->price, "</td><td>",
            $product->currency, "</td><td>",
            $product->availability, "</td><td>",
            $product->created, "</td><td>",
            $this->tag->linkTo("products/edit/".$product->id, "Edit"), "</td><td>",
            $this->tag->linkTo("products/delete/".$product->id, "Delete"), "</td><tr>";

    }
    ?>
    </tbody>
</table>
<hr >
<?php echo $this->tag->linkTo(["products/formCreate", "create", "class" => "btn btn-primary"]); ?>
</div>